name: Remove A13 restriction

on:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Set up
        run: |
          sudo apt-get install -y git wget zip unzip axel python3-pip zipalign apksigner xmlstarlet
          pip3 install ConfigObj

      - name: Set Timezone
        run: |
          echo "Setting timezone"
          sudo timedatectl set-timezone Asia/Jakarta 

      - name: Patching services jar
        run: |
          sudo chmod 777 -R *
          ./patch.sh

      - name: Set current date
        run: echo "::set-env name=BUILD_DATE::$(date +'%Y-%m-%d')"
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: services-jar-patched-${{ github.actor }}-${{ env.BUILD_DATE }}
          path: ./module/*
